tap "oven-sh/bun"
brew "awscli"
brew "fzf"
brew "gh"
brew "git"
brew "mas"
brew "mise"
brew "rustup"
brew "sheldon"
brew "tree"
brew "uv"
brew "zoxide"
brew "oven-sh/bun/bun"
cask "aqua-voice"
cask "chatgpt"
cask "codex"
cask "docker-desktop"
cask "ghostty"
cask "google-chrome"
cask "keycastr"
cask "notion"
cask "session-manager-plugin"
cask "skim"
cask "slack"
cask "spotify"
cask "zed"
mas "Keys", id: 1494642810
mas "Kindle", id: 302584613
mas "Magnet", id: 441258766
mas "Prime Video", id: 545519333
mas "RunCat", id: 1429033973
go "cmd/go"
go "cmd/gofmt"
